Add GHA to publish container images
rh-nfv-int/trex-container-app pull request #3
Opened 2023-02-02 20:59 UTC by tonyskapunk

Create a Makefile to ease the build and push of the images
Use variables in the containerfiles to make easy to change them
Use centOS stream as centos8 is EOL

2023-02-03 00:05 UTC, tonyskapunk commented
A test of the build and publish is in my personal repo, using the same commit: https://github.com/tonyskapunk/trex-container-app/actions/runs/4079319972/jobs/7031139255

btw, I think we need to find a way to reduce the size of the image is more than 1G!

2023-02-03 00:05 UTC, betoredhat approved these changes
Good stuff, lgtm

2023-02-03 14:56 UTC, tkrishtop requested changes

2023-02-03 14:56 UTC, tkrishtop commented on .github/workflows/quay.yml
> +          make all ORG=${ORG} VERSION=${VERSION}
maybe to add a check if this tag already exists before pushing?

2023-02-03 17:17 UTC, tonyskapunk commented on .github/workflows/quay.yml
> +          make all ORG=${ORG} VERSION=${VERSION}
Good call, actually I'll change to use tags instead of push

2023-02-03 17:22 UTC, tonyskapunk commented
> yeah, registry.access.redhat.com/ubi8/python-36 is 847 MB, and it's an EOL btw. python-39 is the current one, 892 MB.

Agreed, I'll do on the next iteration :+1: 
 
> We may use [python-slim + distroless](https://github.com/GoogleContainerTools/distroless/blob/main/examples/python3/Dockerfile) or check if ubi-minimal is already live for python3.9

Python image are tricky, but I agree anything that makes them less heavy would be great

2023-02-04 05:11 UTC, tonyskapunk commented
Test by tag: https://github.com/tonyskapunk/trex-container-app/actions/runs/4089018163

2023-02-06 10:37 UTC, tkrishtop commented on .github/workflows/quay.yml
> +          make all ORG=${ORG} VERSION=${VERSION}
hi @tonyskapunk tbh, I like this version even less because of the [potential problems](https://stackoverflow.com/a/63646054/7775414) and pain with the testing:

> I found out that if the tag was previously created (locally) before the workflow was created, no matter how many times I deleted and re-pushed the tag, it would not trigger until I deleted the tag locally and recreated it. The action does not seem to work for tags created before the workflow.

My initial idea was to have it as a two-step process:

- Check if tag already exists, and if yes, just throw an error during the PR validation
- Push by version during the merge. 
 
Let's sync today to discuss?

2023-02-06 14:35 UTC, tonyskapunk commented on .github/workflows/quay.yml
> +          make all ORG=${ORG} VERSION=${VERSION}
> hi @tonyskapunk tbh, I like this version even less because of the [potential problems](https://stackoverflow.com/a/63646054/7775414) and pain with the testing:
> 
> > I found out that if the tag was previously created (locally) before the workflow was created, no matter how many times I deleted and re-pushed the tag, it would not trigger until I deleted the tag locally and recreated it. The action does not seem to work for tags created before the workflow.
> 

This is strange, we've doing this in operators and the catalog and has not been an issue. The testing has been done already in other org. The testing is only needed once to validate the tagging works. But if there's a need to re-trigger the build is possible and I've done it in the past.

> My initial idea was to have it as a two-step process:
> 
>     * Check if tag already exists, and if yes, just throw an error during the PR validation
> 
>     * Push by version during the merge.
> 

I'm not sure I follow this. :thinking:  Tags don't work as commits, if anyone pushes a tag to a commit in a PR is the same as someone tagging a main branch. It is not expected nor wanted to push a tag into a PR.  Tags must go only in the main branch after a PR. Tags should be part of the release process, that's separate from PRs. This is an example of the release workflow.

- A new change is committed
- A PR is open with those changes
- The PR is tested and approved.
- The PR is merged into the main branch
- The **merge** of the PR is tagged as a new version, this triggers the build and releases a new image for this version.

For now the tagging is manual, same as with operators and the catalog, and that's on purpose, but we can automate it if we wanted.

> Let's sync today to discuss?

Agreed! I'd like to understand better the testing case.

2023-03-01 16:28 UTC, merged